-- Seed legacy feature permission keys for System Administrator profile
INSERT INTO profile_object_permissions (profile_id, object_name, permission_type, parent_module, can_read, can_create, can_edit, can_delete, can_view_all, can_modify_all)
SELECT 
  sp.id,
  v.object_name,
  'feature',
  NULL,
  true, true, true, true, false, false
FROM security_profiles sp
CROSS JOIN (VALUES
  ('admin_dashboard'), ('admin_dashboard_overview'), ('admin_user_list'), ('admin_user_create'),
  ('admin_user_edit'), ('admin_user_delete'), ('admin_user_activate_deactivate'), ('admin_user_reset_password'),
  ('admin_user_hierarchy'), ('admin_approver_management'), ('admin_security_roles_display'),
  ('admin_price_book'), ('admin_price_book_list'), ('admin_price_book_create'), ('admin_price_book_edit'),
  ('admin_price_book_delete'), ('admin_price_book_assignment'), ('admin_attendance_mgmt'),
  ('admin_attendance_live_monitoring'), ('admin_attendance_leave_approvals'),
  ('admin_attendance_regularization_approvals'), ('admin_attendance_holiday_management'),
  ('admin_attendance_leave_balances'), ('admin_attendance_policy_config'), ('admin_attendance_working_days'),
  ('admin_product_mgmt'), ('admin_product_list'), ('admin_product_create'), ('admin_product_edit'),
  ('admin_product_delete'), ('admin_product_categories'), ('admin_product_bulk_import'),
  ('admin_scheme_master'), ('admin_scheme_list'), ('admin_scheme_create'), ('admin_scheme_edit'),
  ('admin_scheme_delete'), ('admin_scheme_applicability'), ('admin_scheme_policy_config'),
  ('admin_vendor_mgmt'), ('admin_vendor_list'), ('admin_vendor_create'), ('admin_vendor_edit'),
  ('admin_vendor_approvals'), ('admin_territories_distributors'), ('admin_territory_management'),
  ('admin_distributor_assignment'), ('admin_region_management'), ('admin_expense_mgmt'),
  ('admin_expense_claims_list'), ('admin_expense_approvals'), ('admin_expense_analytics'),
  ('admin_expense_policy_config'), ('admin_feedback_mgmt'), ('admin_feedback_list'),
  ('admin_competition_insights'), ('admin_branding_requests'), ('admin_operations'),
  ('admin_operations_dashboard'), ('admin_checkin_monitoring'), ('admin_order_monitoring'),
  ('admin_stock_monitoring'), ('admin_gps_track_mgmt'), ('admin_gps_live_location'),
  ('admin_gps_journey_playback'), ('admin_gps_team_tracking'), ('admin_retail_mgmt'),
  ('admin_retailer_list'), ('admin_retailer_verification'), ('admin_retailer_photo_update'),
  ('admin_retailer_territory_assignment'), ('admin_van_sales'), ('admin_van_list'),
  ('admin_van_create'), ('admin_van_edit'), ('admin_van_driver_assignment'),
  ('admin_van_stock_view'), ('admin_van_opening_grn_edits'), ('admin_security_access'),
  ('admin_security_profiles'), ('admin_profile_permissions'), ('admin_user_specific_permissions'),
  ('admin_feature_mgmt'), ('admin_feature_flags'), ('admin_feature_toggle'),
  ('admin_gamification'), ('admin_gamification_config'), ('admin_badges_management'),
  ('admin_rewards_management'), ('admin_redemption_management'), ('admin_retailer_loyalty'),
  ('admin_loyalty_programs'), ('admin_loyalty_points'), ('admin_loyalty_redemptions'),
  ('admin_company_profile'), ('admin_company_details'), ('admin_bank_information'),
  ('admin_header_branding'), ('admin_invoice_mgmt'), ('admin_invoice_list'),
  ('admin_invoice_create'), ('admin_invoice_templates'), ('admin_credit_mgmt'),
  ('admin_credit_scoring_config'), ('admin_credit_limits'), ('admin_notification_setup'),
  ('admin_notification_templates'), ('admin_notification_schedules'), ('admin_recycle_bin'),
  ('admin_recycle_bin_settings'), ('admin_permanent_deletion_logs'), ('admin_restore_deleted_items'),
  ('admin_distributor_portal'), ('admin_portal_users'), ('admin_portal_orders'),
  ('admin_portal_inventory'), ('admin_portal_claims'), ('admin_portal_support'),
  ('admin_portal_ideas'), ('admin_target_vs_actual'), ('admin_target_setting'),
  ('admin_target_tracking'), ('admin_hierarchy_targets'), ('admin_hierarchy_target_setup'),
  ('admin_target_cascade'), ('admin_allocation_methods'),
  ('attendance_check_in_out'), ('attendance_face_verification'), ('attendance_leave_applications'),
  ('attendance_regularization_requests'), ('attendance_holiday_list'), ('attendance_timeline_view'),
  ('attendance_journey_map'), ('attendance_statistics'), ('attendance_photo_capture'),
  ('visit_auto_plan'), ('visit_auto_plan_view'), ('visit_auto_plan_generate'), ('visit_auto_plan_edit'),
  ('visit_all_beat'), ('visit_all_beat_view'), ('visit_all_beat_select'), ('visit_all_beat_retailers'),
  ('visit_retailers'), ('visit_retailer_list'), ('visit_retailer_check_in'),
  ('visit_retailer_order_entry'), ('visit_retailer_no_order'), ('visit_retailer_create_visit'),
  ('visit_summary'), ('visit_summary_view'), ('visit_summary_export'), ('visit_summary_insights'),
  ('visit_timeline'), ('visit_timeline_view'), ('visit_timeline_details'),
  ('visit_gps_track'), ('visit_gps_track_view'), ('visit_gps_track_playback'),
  ('visit_van_stock'), ('visit_van_stock_view'), ('visit_van_stock_manage'),
  ('visit_activity'), ('visit_activity_view'), ('visit_activity_log'), ('visit_activity_sync'),
  ('visit_todays_progress'), ('visit_todays_progress_view'), ('visit_points_gamification'),
  ('visit_ai_recommendations'),
  ('retailer_list'), ('retailer_add'), ('retailer_detail'), ('retailer_category_filter'),
  ('retailer_beat_assignment'), ('retailer_credit_score'), ('retailer_order_history'),
  ('retailer_analytics'), ('retailer_bulk_import'), ('retailer_location_map'),
  ('target_overview'), ('target_period_selection'), ('target_achievement_percentage'),
  ('target_territory_performance'), ('target_beat_performance'), ('target_retailer_performance'),
  ('target_ai_recommendations'), ('target_shortfall_analysis'),
  ('performance_overall'), ('performance_territory_breakdown'), ('performance_beat_breakdown'),
  ('performance_retailer_breakdown'), ('performance_period_comparison'), ('performance_trend_analysis'),
  ('performance_leaderboard'),
  ('analytics_business_summary'), ('analytics_beat_details'), ('analytics_retailer_details'),
  ('analytics_order_details'), ('analytics_product_breakdown'), ('analytics_pending_payments'),
  ('analytics_user_filter'), ('analytics_date_range_picker'), ('analytics_performance_calendar'),
  ('analytics_leaderboard'),
  ('institutional_dashboard'), ('institutional_leads'), ('institutional_accounts'),
  ('institutional_contacts'), ('institutional_opportunities'), ('institutional_quotes'),
  ('institutional_proposals'), ('institutional_pipeline'),
  ('beat_list'), ('beat_create'), ('beat_detail'), ('beat_schedule'),
  ('beat_retailer_assignment'), ('beat_travel_allowance'), ('beat_analytics'),
  ('expense_beat_allowance'), ('expense_claims'), ('expense_claim_history'),
  ('expense_approval_status'), ('expense_distance_calculation'),
  ('gamification_leaderboard'), ('gamification_badges'), ('gamification_rewards'),
  ('gamification_redemption'), ('gamification_points_history'),
  ('distributor_list'), ('distributor_add'), ('distributor_edit'), ('distributor_detail'),
  ('distributor_retailer_mapping'), ('distributor_coverage_area'), ('distributor_fleet_size'),
  ('distributor_partnership_status'),
  ('territory_list'), ('territory_map'), ('territory_performance'),
  ('competition_competitor_list'), ('competition_competitor_detail'), ('competition_sku_comparison'),
  ('competition_sales_team_size'), ('competition_regional_presence'), ('competition_news_articles'),
  ('competition_swot_analysis'),
  ('scheme_list'), ('scheme_details'), ('scheme_eligibility'),
  ('packing_list_view'), ('packing_create'), ('packing_detail'), ('packing_mark_delivered'),
  ('delivery_list'), ('delivery_detail'), ('delivery_status_update'),
  ('invoice_list'), ('invoice_detail'), ('invoice_pdf_view'),
  ('credit_overview'), ('credit_retailer_detail'), ('credit_score_card'),
  ('feedback_list'), ('feedback_detail'), ('feedback_analytics'),
  ('return_list'), ('return_detail'), ('return_analytics'),
  ('van_stock_view'), ('van_sales_summary'), ('van_route_plan'),
  ('homepage_greeting'), ('homepage_quick_stats'), ('homepage_target_progress'),
  ('homepage_quick_add'), ('homepage_quick_links'), ('homepage_attendance'),
  ('homepage_visit_plan'), ('homepage_performance'), ('homepage_target_achievement'),
  ('notification_list'), ('notification_detail'), ('notification_preferences'),
  ('competency'), ('competency_dashboard'), ('competency_detail'), ('competency_team'),
  ('profile_overview'), ('profile_edit'), ('profile_activity_log'),
  ('admin_pincode_master'), ('admin_pincode_list'), ('admin_pincode_search'),
  ('admin_pincode_import'), ('admin_pincode_edit'),
  ('admin_tax_master'), ('tax_master_list'), ('tax_master_create'),
  ('tax_master_edit'), ('tax_master_delete'), ('tax_master_mapping'),
  ('admin_retailer_ext_db'), ('admin_retailer_ext_list'), ('admin_retailer_ext_import'),
  ('admin_retailer_ext_export'), ('admin_retailer_ext_match'),
  ('admin_notification_rules'), ('admin_notification_rules_list'), ('admin_notification_rules_create'),
  ('admin_notification_rules_edit'), ('admin_notification_rules_delete'),
  ('admin_system_settings'), ('admin_system_general'), ('admin_system_email'),
  ('admin_system_sms'), ('admin_settings_backup'),
  ('admin_user_mgmt'), ('admin_user_mgmt_list'), ('admin_user_mgmt_create'),
  ('admin_user_mgmt_edit'), ('admin_user_mgmt_hierarchy'),
  ('user_mgmt_list'), ('user_mgmt_create'), ('user_mgmt_edit'),
  ('user_mgmt_delete'), ('user_mgmt_activate'), ('user_mgmt_reset_password'), ('user_mgmt_hierarchy')
) AS v(object_name)
WHERE sp.name = 'System Administrator'
ON CONFLICT (profile_id, object_name, permission_type) 
DO UPDATE SET can_read = true, can_create = true, can_edit = true, can_delete = true;