// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihdkqgiesgichzgrqocc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImloZGtxZ2llc2dpY2h6Z3Jxb2NjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM0MjM0MzAsImV4cCI6MjA5ODk5OTQzMH0.I33gT9uRKscNDAGULWFIUQlidY2ETrMbkR2RjuIPLE0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});